# 🏆Proyecto PE 🏆
## Actividad introductoria de python

En este notebook se estará trabajando el proyecto final.

**Nombre:** [NOMBRE]

**Correo Electrónico:** [CORREO ELECTRÓNICO]

**Fecha Límite de Entrega:** 2025

**Enviar notebook final en formato .ipynb con el asunto del correo "Proyecto Final Python" a:**

juan.garza@udem.edu

# Objetivos del proyecto 🏁
1. **Desarrollar Habilidades Prácticas de Análisis de Datos 📊**: Aplicar técnicas de Pandas y Matplotlib/Seaborn para resolver problemas de análisis de datos. Esto incluye limpieza de datos, operaciones matemáticas y estadísticas y visualización de datos.

2. **Fomentar el Pensamiento Crítico y la Resolución de Problemas 💡**: A través de ejercicios, aplicar lo aprendido en situaciones nuevas y desafiantes, desarrollando así habilidades de pensamiento crítico y resolución de problemas en el contexto del análisis de datos.

# Ayuda 🤖📔💻👩🏻🧑🏻👨🏻‍🏫👨🏻‍🏫👩🏻‍🏫
1. **Asistentes de IAG**: Puedes utilizar tu asistente de IAG favorito para realizar este proyecto: ChatGPT, Bard, Copilot
2. **Notebooks de la clase** : Puedes utilizar el código de cualquiera de las notebooks que hemos trabajado en las sesiones pasadas
3. **Internet**: Cualquier duda puedes buscarlo en Internet, páginas como StackOverflow y las documentaciones técnicas de las librerías de Python te pueden servir
4. **Compañeros de clase**: Puedes pedirle ayuda a tus compañeros y compañeras de clase.
5. **Profesor**: Aquí estamos para apoyarte con cualquier duda o comentario.

  - Juan Baldemar Garza V - juan.garza@udem.edu

# Dataset
Para el proyecto final estaremos trabajando con una base de datos disponible en UC Irvine Machine Learning Repository:

[Adult](https://archive.ics.uci.edu/dataset/2/adult)

A continuación enlistamos las diferentes variables del dataset:

- `income`: >50K, <=50K.
- `age`: continuous.
- `workclass`: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- `fnlwgt`: continuous.
- `education`: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- `education-num`: continuous.
- `marital-status`: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- `occupation`: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- `relationship`: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- `race`: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- `sex`: Female, Male.
- `capital-gain`: continuous.
- `capital-loss`: continuous.
- `hours-per-week`: continuous.
- `native-country`: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.


**Referencia de la base de datos:**

Becker,Barry and Kohavi,Ronny. (1996). Adult. UCI Machine Learning Repository. https://doi.org/10.24432/C5XW20.

# Importar liberías

In [1]:
#  primero instala la librería de ucimlrepo
!pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.5.20)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [2]:
# importa las librerías que vamos a estar utilizando para este proyecto
from ucimlrepo import fetch_ucirepo
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Importar datos del dataset *Adult*

In [3]:
# extraer dataset
adult = fetch_ucirepo(id=2)

print(type(adult))

print(adult.keys())

<class 'ucimlrepo.dotdict.dotdict'>
dict_keys(['data', 'metadata', 'variables'])

In [4]:
# metadata
adult.metadata

{'uci_id': 2,
 'name': 'Adult',
 'repository_url': 'https://archive.ics.uci.edu/dataset/2/adult',
 'data_url': 'https://archive.ics.uci.edu/static/public/2/data.csv',
 'abstract': 'Predict whether annual income of an individual exceeds $50K/yr based on census data. Also known as "Census Income" dataset. ',
 'area': 'Social Science',
 'tasks': ['Classification'],
 'characteristics': ['Multivariate'],
 'num_instances': 48842,
 'num_features': 14,
 'feature_types': ['Categorical', 'Integer'],
 'demographics': ['Age', 'Income', 'Education Level', 'Other', 'Race', 'Sex'],
 'target_col': ['income'],
 'index_col': None,
 'has_missing_values': 'yes',
 'missing_values_symbol': 'NaN',
 'year_of_dataset_creation': 1996,
 'last_updated': 'Tue Sep 24 2024',
 'dataset_doi': '10.24432/C5XW20',
 'creators': ['Barry Becker', 'Ronny Kohavi'],
 'intro_paper': None,
 'additional_info': {'summary': "Extraction was done by Barry Becker from the 1994 Census database.  A set of reasonably clean records was extracted using the following conditions: ((AAGE>16) && (AGI>100) && (AFNLWGT>1)&& (HRSWK>0))\n\nPrediction task is to determine whether a person's income is over $50,000 a year.\n",
  'purpose': None,
  'funded_by': None,
  'instances_represent': None,
  'recommended_data_splits': None,
  'sensitive_data': None,
  'preprocessing_description': None,
  'variable_info': 'Listing of attributes:\r\n\r\n>50K, <=50K.\r\n\r\nage: continuous.\r\nworkclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.\r\nfnlwgt: continuous.\r\neducation: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.\r\neducation-num: continuous.\r\nmarital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.\r\noccupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.\r\nrelationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.\r\nrace: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.\r\nsex: Female, Male.\r\ncapital-gain: continuous.\r\ncapital-loss: continuous.\r\nhours-per-week: continuous.\r\nnative-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.',
  'citation': None}}

In [5]:
# variables
adult.variables

,name,role,type,demographic,description,units,missing_values
0,age,Feature,Integer,Age,N/A,None,no
1,workclass,Feature,Categorical,Income,"Private, Self-emp-not-inc, Self-emp-inc, Feder...",None,yes
2,fnlwgt,Feature,Integer,None,None,None,no
3,education,Feature,Categorical,Education Level,"Bachelors, Some-college, 11th, HS-grad, Prof-...",None,no
4,education-num,Feature,Integer,Education Level,None,None,no
5,marital-status,Feature,Categorical,Other,"Married-civ-spouse, Divorced, Never-married, S...",None,no
6,occupation,Feature,Categorical,Other,"Tech-support, Craft-repair, Other-service, Sal...",None,yes
7,relationship,Feature,Categorical,Other,"Wife, Own-child, Husband, Not-in-family, Other...",None,no
8,race,Feature,Categorical,Race,"White, Asian-Pac-Islander, Amer-Indian-Eskimo,...",None,no
9,sex,Feature,Binary,Sex,"Female, Male.",None,no
10,capital-gain,Feature,Integer,None,None,None,no
11,capital-loss,Feature,Integer,None,None,None,no
12,hours-per-week,Feature,Integer,None,None,None,no
13,native-country,Feature,Categorical,Other,"United-States, Cambodia, England, Puerto-Rico,...",None,yes
14,income,Target,Binary,Income,">50K, <=50K.",None,no

In [6]:
# data como un pandas dataframe
vars = adult.data.features
income = adult.data.targets

In [ ]:
vars

In [ ]:
income

# Procesamiento de datos

In [9]:
# unir vars e income en un solo dataframe llamado df usando la función pd.concat()
df = pd.concat([vars,income],axis = 1)

In [13]:
# obtener atributos del dataframe df, imprimirlos
# shape
print("Tamaño del dataframe:\n", df.shape)

# tipos de datos
print("\nTipo de datos:\n",df.describe())

# nombre de columnas
print("\nNombre de columnas: \n",df.columns)

Tamaño del dataframe:
 (48842, 15)

Tipo de datos:
                 age        fnlwgt  education-num  capital-gain  capital-loss  \
count  48842.000000  4.884200e+04   48842.000000  48842.000000  48842.000000
mean      38.643585  1.896641e+05      10.078089   1079.067626     87.502314
std       13.710510  1.056040e+05       2.570973   7452.019058    403.004552
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000
25%       28.000000  1.175505e+05       9.000000      0.000000      0.000000
50%       37.000000  1.781445e+05      10.000000      0.000000      0.000000
75%       48.000000  2.376420e+05      12.000000      0.000000      0.000000
max       90.000000  1.490400e+06      16.000000  99999.000000   4356.000000

       hours-per-week
count    48842.000000
mean        40.422382
std         12.391444
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000

Nombre de columnas:
 Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [14]:
#checar si hay valores nulos usando las funciones isna() y sum() en ese orden
df.isna().sum()

age                 0
workclass         963
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation        966
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
income              0
dtype: int64

In [15]:
#si hay valores nulos, eliminarlos, y guardar en un nuevo dataframe df_2 usando dropna()
df_2 = df.dropna()

#revisar que sí se hayan eliminado los valores nulos
df_2.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [ ]:
# checar valores duplicados utlizando la función duplicated(keep = False) en df_2 y guárdalo en una nueva variable llamado duplicados
# este va a generar una serie de True y False para luego poder identificar cuáles son las filas que tienen valores duplicados
duplicados = df_2.______

# filtra df_2 por los valores duplicados y guárdalo en un nuevo dataframe valores_duplicados
valores_duplicados = df_2[______]

# enseña valores_duplicados, ordena por las columnas age y fnlwgt usando la función sort_values y el parámetro by
valores_duplicados.______(by = ["age","fnlwgt"])

In [ ]:
# elimina los duplicados del df_2 usando la función drop_duplicates() y guárdalo en un nuevo dataframe df_3
df_3 = df_2.______

# imprime el shape de df_2 y df_3 en ese orden para ver que se hayan eliminado correctamente los valores duplicados
print(______, ______)

🚩CHECKPOINT 🚩

Si hiciste bien todo lo anterior, al imprimir el shape de df_2 y df_3 en ese orden te debería dar el siguiente resultado:

**(47621, 15) (47592, 15)**

In [ ]:
# Agrupar las columnas por tipo de datos
agrupar_por_dtype = df_3.columns.to_series().groupby(df_3.dtypes).groups

# Imprime los valores únicos de cada columna junto con su tipo de dato
for dtype, columns in agrupar_por_dtype.items():
    print(f'Tipo de dato: {dtype}')
    for col in columns:
        unique_values = df_3[col].unique()
        print(f'Columna: {col}\nValores únicos: {unique_values}\n')

Al revisar los valores únicos de las columnas, a primera vista nos damos cuenta que en las columnas `workclass`, `occupation` y `native-country` contienen un valor de "?"

También, podemos ver que en la columna de `income` tenemos categorías duplicadas '<=50K'/ con '<=50K.' y '>50K' con '>50K.'

Trabajemos para arreglar estas columnas.

In [ ]:
df_4 = df_3.copy()
# Reemplazar "?" con "Indefinido" en las columnas que identificamos usando la función replace
#define una lista de las columans que vamos a ajustar
columnas_a_ajustar = [______, ______, ______]
#utiliza la función replace para ajustar esas columnas
df_4.loc[:, columnas_a_ajustar] = df_4[columnas_a_ajustar].______('?', 'Indefinido')

# Reemplazar valores en la columna income, <=50K. con <=50K y >50K. con >50K
df_4.loc[:, ______] = df_4['income'].______({'<=50K.': '<=50K', '>50K.': '>50K'})

# Imprimir  valores de la columna income para revisar que sí se hayan aplicado los cambios
unicos_income = df_4['income'].unique()
unicos_country = df_4['native-country'].unique()
print(f'Columna: income\nValores: {unicos_income}\n')
print(f'Columna: native-country\nValores: {unicos_country}\n')

# Análisis estadístico básico

In [ ]:
# utiliza la función describe() en df_4 para obtener estadísticas sobre las columnas categóricas
______.______

In [ ]:
# calcula la edad promedio de cada país utilizando groupby en native-country y ordena de mayor a menor usando sort_values ajustando el parámetros ascending a False
df_4.______["age"].mean().______(ascending = ______)

💡PREGUNTA💡

**¿Cuál es el país con la mayor edad promedio?**

*RESPUESTA*

In [ ]:
# calcula la edad promedio por país e ingreso utilizando groupby y ordena de mayor a menor
grupo_2 = df_4.groupby([______,______])["age"].mean().sort_values(ascending = False).reset_index()

# cómo se comporta México y Estados Unidos
# define dos condiciones, una para cada país
c_1 = ______ == "Mexico"
c_2 = grupo_2["native-country"] == ______

# filtra grupo_2 por esas condiciones en dónde native-country es Mexico o United-States
print(grupo_2[(______) ______ (______)])

In [ ]:
# ahora utiliza la función isin
lista_paises = ["Mexico","United-States"]
print(grupo_2[grupo_2["native-country"].isin(lista_paises)])

🚩CHECKPOINT 🚩

Si hiciste bien todo lo anterior, el resultado utilizando la función isin() debería ser el mismo al de filtrar grupo_2 por las dos condiciones.

💡PREGUNTA💡

**De los registros donde el país de origen es México, ¿cuál es la edad promedio de las personas que ganan más de 50K? ¿Cuál es la edad promedio de los registros donde el país de origen es Estados Unidos para las personas que ganan menos de o igual a 50K?**

*RESPUESTA*

In [ ]:
# calcula cuántos registros hay por país y ordena de mayor a menor utilizando la función count()
df_4.groupby("native-country")["age"].______.sort_values(ascending = False)

💡PREGUNTA💡

**¿Cuántos registros tiene México?**

*RESPUESTA*

In [ ]:
# crea un nuevo df con sólo valores de Estados Unidos utilizando df_4
df_usa = df_4[______[______] == ______]

# para los siguientes ejercicios, sólo estaremos utilizando las columnas 'age','education', 'income','marital_status'
# selecciona esas columnas
columnas_interes = [______,______,______,______]
df_usa_2 =______[______]

# imprime el shape del df_usa_2
print(______.______)

🚩CHECKPOINT 🚩

Si hiciste bien todo lo anterior, el resultado del shape de df_usa_2 debería de ser:

**(42936, 4)**

# Visualizaciones
Para esta última sección vamos a tener que realizar las siguientes visualizaciones:


**Gráfica de Barras:** Número de registros por nivel de educación

**Boxplot:** Edad por estado civil e ingreso

**Kernel Density Plot:** Distribución de edad por estado civil

In [ ]:
# Contar el número de filas para cada categoría de educación usando value_counts()
education_counts = df_usa_2['education'].______

plt.figure(figsize=(10, 6))  # Establecer el tamaño de la figura
# Crear un gráfico de barras utilizando plt.bar
______.______(education_counts.index, education_counts.values)

# Establecer etiquetas y título
plt.xlabel('Educación')
plt.ylabel('Número de Registros')
# Define el título como 'Número de Registros por nivel de educación'
plt.title(______)

# Rotar etiquetas del eje x  por 45 grados para una mejor visibilidad
plt.xticks(rotation=______)

# Mostrar el gráfico
plt.tight_layout()  # Ajustar el diseño para una mejor apariencia
plt.show()

📊📈 ANÁLISIS 📊📈

**Describe una conclusión que puedas derivar de la gráfica anterior:**

*RESPUESTA*

In [ ]:
sns.set_theme(style="ticks", palette="bright")

# Crear un boxplot utilizando Seaborn función boxplot
# - El eje x es "age"
# - El eje y es "marital-status"
# - Hue (color) está determinado por "income"
# - Los datos provienen del DataFrame df_usa_2
sns.______(x=______, y=______,
            hue =______, palette=["m", "g"],
            data=______)

sns.despine(offset=10, trim=True)

📊📈 ANÁLISIS 📊📈

**Describe una conclusión que puedas derivar de la gráfica anterior:**

*RESPUESTA*

In [ ]:
# Configuración de Seaborn para un fondo blanco y una figura sin color de fondo
sns.set_theme(style="white", rc={"axes.facecolor": (0, 0, 0, 0)})

# Definir una paleta personalizada con tonos de naranja excluyendo amarillo
custom_palette = sns.color_palette("YlOrRd", n_colors=5)[1:]

# Aumentar el tamaño de la figura para dar más espacio a los subplots
plt.figure(figsize=(16, 9))

# Inicializar el objeto FacetGrid row y hue marital-status
g = sns.FacetGrid(df_usa_2, row=______, hue=______, aspect=15, height=1, palette=custom_palette)

# Dibujar los kernel density plots usando la columna age
g.map(sns.kdeplot, ______,
      bw_adjust=.5, clip_on=False,
      fill=True, alpha=1, linewidth=1.5)

g.map(sns.kdeplot, "age", clip_on=False, color="w", lw=2, bw_adjust=.5)

# Pasar color=None a refline() utiliza la asignación de color 'hue'
g.refline(y=0, linewidth=2, linestyle="-", color=None, clip_on=False)

# Definir y usar una función simple para etiquetar el gráfico en coordenadas del eje
def label(x, color, label):
    ax = plt.gca()
    ax.text(1, .2, label, fontweight="bold", color=color,
            ha="left", va="center", transform=ax.transAxes)

g.map(label, "age")

# Ajustar las subtramas para que se superpongan
g.figure.subplots_adjust(hspace=-.25)

# Eliminar detalles de los ejes que no se integran bien con la superposición
g.set_titles("")
g.set(yticks=[], ylabel="")
g.despine(bottom=True, left=True)

# Mostrar el gráfico
plt.show()

📊📈 ANÁLISIS 📊📈

**Describe una conclusión que puedas derivar de la gráfica anterior:**

*RESPUESTA*

🎉🎉🎉FELICIDADES 🎉🎉🎉

¡Terminaste el proyecto pe!

Has completado con éxito. 🐍💻 Tu dedicación y esfuerzo se han reflejado en un trabajo excepcional. ¡Sigue así y alcanza tus metas en el mundo de la analítica de datos con Python! 📊📈

**Recuerda enviar este notebook en formato .ipynb antes de la fecha indicada.

UDEM
juan.garza@udem.edu